FROM node:24.4.1@sha256:c7a63f857d6dc9b3780ceb1874544cc22f3e399333c82de2a46de0049e841729

WORKDIR /app

# Copy only package.json and package-lock.json first.
# This allows us to cache the npm install layer.
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Now copy the rest of the files.
COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

# docker build --file Dockerfile.v3 --tag docker-demo:v3 .
# docker run -it --rm --publish 3000:3000 docker-demo:v3
