# Base image to start from.
FROM node:24.4.1@sha256:c7a63f857d6dc9b3780ceb1874544cc22f3e399333c82de2a46de0049e841729

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

# docker build --file Dockerfile.v2 --tag docker-demo:v2 .
# docker run -it --rm --publish 3000:3000 docker-demo:v2
